### PR TITLE
Team Profile: PR21-26

### PR DESCRIPTION
**Pull request by ndowkunda**
** Feedback functionality added**
- combined with PR21-43 ticket
-  feedback form added
-  post request for feedback added
-  feedback input handled via click action
-  cypress feature tests added to assert feedback input data is displayed correctly

### CODE REVIEW

**Review by dearshrewdwit — CHANGES_REQUESTED** [review]
Can you check with your team the API url for the profiles endpoint- It looks like to me it's plural: `/api/profiles/`

If so, can you change it in test and source code?

**Review by AntMousinho — DISMISSED** [review]
Changed the api endpoints to match the backend app

**Comment by dearshrewdwit** [comment]
OK before it's merged in to main please squash unncessary commits

Find the earliest new commit using `git log`. Note down the commit hash. Then:
```sh
git rebase -i <first 6 chars of commit hash>
```
within the editor, use `f` to squash unnecessary commits. Then `esc`, `:wq` to confirm.

Once the rebase is resolved, 
```sh
git push origin +PR21-26` to force push in order to overwrite the commit history in GitHub
```

**Review by dearshrewdwit — DISMISSED** [review]

**Comment by dearshrewdwit** [comment]
Uh oh! You can check CI warnings using `CI=true npm run build`

**Review by dearshrewdwit — APPROVED** [review]

**Review by petraboldi — APPROVED** [review]

**Pull request merged**
